// src/pages/spa/component/Nav.jsx
import React from 'react';
import PropTypes from 'prop-types';
import header from '../../_commons/header.ejs';

const Nav = ({ location }) => {
  const ejs = header({
    active: location.pathname === '/spa/page3' ? 'page3' : 'page4',
  });
  // eslint-disable-next-line react/no-danger
  return <div dangerouslySetInnerHTML={{ __html: ejs }} />;
};

Nav.propTypes = {
  location: PropTypes.shape({
    hash: PropTypes.string,
    pathname: PropTypes.string,
    search: PropTypes.string,
  }).isRequired,
};

export default Nav;

// src/pages/vue/components/Nav.vue
<template>
  <!-- eslint-disable-next-line vue/no-v-html -->
  <div v-html="ejs" />
</template>

<script>
import header from '../../_commons/header.ejs';

export default {
  name: 'Nav',
  data: () => ({
    ejs: header({ active: 'page5' }),
  }),
};
</script>

<style>
  .header {
    margin-bottom: 30px;
  }
</style>
